# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/saidbounasser/projects/DUNE/ElectricalMethod/firmware/source/dwa_ps/dwa_ps.srcs/sources_1/ip/fifo_autoDatacollection/fifo_autoDatacollection.xci
# IP: The module: 'fifo_autoDatacollection' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/saidbounasser/projects/DUNE/ElectricalMethod/firmware/source/dwa_ps/dwa_ps.srcs/sources_1/ip/fifo_autoDatacollection/fifo_autoDatacollection.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_autoDatacollection'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/saidbounasser/projects/DUNE/ElectricalMethod/firmware/source/dwa_ps/dwa_ps.srcs/sources_1/ip/fifo_autoDatacollection/fifo_autoDatacollection_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_autoDatacollection'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/saidbounasser/projects/DUNE/ElectricalMethod/firmware/source/dwa_ps/dwa_ps.srcs/sources_1/ip/fifo_autoDatacollection/fifo_autoDatacollection.xci
# IP: The module: 'fifo_autoDatacollection' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/saidbounasser/projects/DUNE/ElectricalMethod/firmware/source/dwa_ps/dwa_ps.srcs/sources_1/ip/fifo_autoDatacollection/fifo_autoDatacollection.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_autoDatacollection'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/saidbounasser/projects/DUNE/ElectricalMethod/firmware/source/dwa_ps/dwa_ps.srcs/sources_1/ip/fifo_autoDatacollection/fifo_autoDatacollection_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_autoDatacollection'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
