# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/dwa_ps_bd.bd
# Block Designs: The module: 'dwa_ps_bd' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_processing_system7_0_0/dwa_ps_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dwa_ps_bd_processing_system7_0_0 || ORIG_REF_NAME==dwa_ps_bd_processing_system7_0_0} -quiet] -quiet

# IP: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_ps7_0_axi_periph_0/dwa_ps_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dwa_ps_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==dwa_ps_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_rst_ps7_0_100M_1/dwa_ps_bd_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dwa_ps_bd_rst_ps7_0_100M_1 || ORIG_REF_NAME==dwa_ps_bd_rst_ps7_0_100M_1} -quiet] -quiet

# IP: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_auto_pc_0/dwa_ps_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dwa_ps_bd_auto_pc_0 || ORIG_REF_NAME==dwa_ps_bd_auto_pc_0} -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_processing_system7_0_0/dwa_ps_bd_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dwa_ps_bd_processing_system7_0_0 || ORIG_REF_NAME==dwa_ps_bd_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_rst_ps7_0_100M_1/dwa_ps_bd_rst_ps7_0_100M_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dwa_ps_bd_rst_ps7_0_100M_1 || ORIG_REF_NAME==dwa_ps_bd_rst_ps7_0_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_rst_ps7_0_100M_1/dwa_ps_bd_rst_ps7_0_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dwa_ps_bd_rst_ps7_0_100M_1 || ORIG_REF_NAME==dwa_ps_bd_rst_ps7_0_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_rst_ps7_0_100M_1/dwa_ps_bd_rst_ps7_0_100M_1_ooc.xdc

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_auto_pc_0/dwa_ps_bd_auto_pc_0_ooc.xdc

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/dwa_ps_bd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dwa_ps_bd'. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/dwa_ps_bd.bd
# Block Designs: The module: 'dwa_ps_bd' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_processing_system7_0_0/dwa_ps_bd_processing_system7_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dwa_ps_bd_processing_system7_0_0 || ORIG_REF_NAME==dwa_ps_bd_processing_system7_0_0} -quiet] -quiet

# IP: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_ps7_0_axi_periph_0/dwa_ps_bd_ps7_0_axi_periph_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dwa_ps_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==dwa_ps_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_rst_ps7_0_100M_1/dwa_ps_bd_rst_ps7_0_100M_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dwa_ps_bd_rst_ps7_0_100M_1 || ORIG_REF_NAME==dwa_ps_bd_rst_ps7_0_100M_1} -quiet] -quiet

# IP: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_auto_pc_0/dwa_ps_bd_auto_pc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dwa_ps_bd_auto_pc_0 || ORIG_REF_NAME==dwa_ps_bd_auto_pc_0} -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_processing_system7_0_0/dwa_ps_bd_processing_system7_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dwa_ps_bd_processing_system7_0_0 || ORIG_REF_NAME==dwa_ps_bd_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_rst_ps7_0_100M_1/dwa_ps_bd_rst_ps7_0_100M_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dwa_ps_bd_rst_ps7_0_100M_1 || ORIG_REF_NAME==dwa_ps_bd_rst_ps7_0_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_rst_ps7_0_100M_1/dwa_ps_bd_rst_ps7_0_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dwa_ps_bd_rst_ps7_0_100M_1 || ORIG_REF_NAME==dwa_ps_bd_rst_ps7_0_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_rst_ps7_0_100M_1/dwa_ps_bd_rst_ps7_0_100M_1_ooc.xdc

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/ip/dwa_ps_bd_auto_pc_0/dwa_ps_bd_auto_pc_0_ooc.xdc

# XDC: /home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/dwa_ps_bd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dwa_ps_bd'. Do not add the DONT_TOUCH constraint.
