# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nate/projects/duneWireTension/firmware/scripts/.Xil/Vivado-5534-lt2/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub.xci
# IP: The module: 'dbg_hub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nate/projects/duneWireTension/firmware/scripts/.Xil/Vivado-5534-lt2/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/firmware/scripts/.Xil/Vivado-5534-lt2/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/nate/projects/duneWireTension/firmware/scripts/.Xil/Vivado-5534-lt2/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub.xci
# IP: The module: 'dbg_hub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nate/projects/duneWireTension/firmware/scripts/.Xil/Vivado-5534-lt2/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/nate/projects/duneWireTension/firmware/scripts/.Xil/Vivado-5534-lt2/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbg_hub'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
