set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/clk_sysclk_mmcm/clk_sysclk_mmcm/clk_sysclk_mmcm_in_context.xdc rfile:../../../../source/cores/ip/clk_sysclk_mmcm/clk_sysclk_mmcm/clk_sysclk_mmcm_in_context.xdc id:1 order:EARLY scoped_inst:clk_sysclk_mmcm_inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/vio_ctrl/vio_ctrl/vio_ctrl_in_context.xdc rfile:../../../../source/cores/ip/vio_ctrl/vio_ctrl/vio_ctrl_in_context.xdc id:2 order:EARLY scoped_inst:vio_ctrl_inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/fifo_autoDatacollection/fifo_autoDatacollection/fifo_autoDatacollection_in_context.xdc rfile:../../../../source/cores/ip/fifo_autoDatacollection/fifo_autoDatacollection/fifo_autoDatacollection_in_context.xdc id:3 order:EARLY scoped_inst:fifo_autoDatacollection_inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/fifo_adcData/fifo_adcData/fifo_adcData_in_context.xdc rfile:../../../../source/cores/ip/fifo_adcData/fifo_adcData/fifo_adcData_in_context.xdc id:4 order:EARLY scoped_inst:{genCh[2].fifo_adcData_ch}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/fifo_adcData/fifo_adcData/fifo_adcData_in_context.xdc rfile:../../../../source/cores/ip/fifo_adcData/fifo_adcData/fifo_adcData_in_context.xdc id:5 order:EARLY scoped_inst:{genCh[1].fifo_adcData_ch}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/fifo_adcData/fifo_adcData/fifo_adcData_in_context.xdc rfile:../../../../source/cores/ip/fifo_adcData/fifo_adcData/fifo_adcData_in_context.xdc id:6 order:EARLY scoped_inst:{genCh[0].fifo_adcData_ch}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc rfile:../../../../source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc id:7 order:EARLY scoped_inst:ila_xadc_all} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc rfile:../../../../source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc id:8 order:EARLY scoped_inst:ila_xadc_fifoAutoSparse} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc rfile:../../../../source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc id:9 order:EARLY scoped_inst:ila_xadc_fifoAuto} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc rfile:../../../../source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc id:10 order:EARLY scoped_inst:ila_xadc_controller} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc rfile:../../../../source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc id:11 order:EARLY scoped_inst:{genCh[2].ila_xadc_ch}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc rfile:../../../../source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc id:12 order:EARLY scoped_inst:{genCh[1].ila_xadc_ch}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc rfile:../../../../source/cores/ip/ila_xadc/ila_xadc/ila_xadc_in_context.xdc id:13 order:EARLY scoped_inst:{genCh[0].ila_xadc_ch}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ip/xadc_senseWire/xadc_senseWire/xadc_senseWire_in_context.xdc rfile:../../../../source/cores/ip/xadc_senseWire/xadc_senseWire/xadc_senseWire_in_context.xdc id:14 order:EARLY scoped_inst:xadc_senseWire_inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/constraints/system.xdc rfile:../../../../source/constraints/system.xdc id:15} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5.000 -name sysclk_p [get_ports sysclk_p]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_sysclk_mmcm_inst/clk_out1 -source [get_ports sysclk_p] -edges {1 2 3} -edge_shift {0.000 17.500 35.000} [get_pins clk_sysclk_mmcm_inst/clk_out1]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_sysclk_mmcm_inst/clk_out2 -source [get_ports sysclk_p] -edges {1 2 3} -edge_shift {0.000 7.500 15.000} [get_pins clk_sysclk_mmcm_inst/clk_out2]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_sysclk_mmcm_inst/clk_out3 -source [get_ports sysclk_p] -edges {1 2 3} -edge_shift {0.000 2.500 5.000} [get_pins clk_sysclk_mmcm_inst/clk_out3]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_sysclk_mmcm_inst/clk_out4 -source [get_ports sysclk_p] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins clk_sysclk_mmcm_inst/clk_out4]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_sysclk_mmcm_inst/clk_out5 -source [get_ports sysclk_p] -edges {1 2 3} -edge_shift {0.000 -1.250 -2.500} [get_pins clk_sysclk_mmcm_inst/clk_out5]
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_sysclk_mmcm_inst/clk_out6 -source [get_ports sysclk_p] -edges {1 2 3} -edge_shift {0.000 37.500 75.000} [get_pins clk_sysclk_mmcm_inst/clk_out6]
set_property src_info {type:SCOPED_XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports sysclk_n]
set_property src_info {type:SCOPED_XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports sysclk_n]
set_property src_info {type:SCOPED_XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports sysclk_p]
set_property src_info {type:SCOPED_XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports sysclk_p]
set_property src_info {type:SCOPED_XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells clk_sysclk_mmcm_inst]
current_instance vio_ctrl_inst
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells vio_ctrl_inst]
current_instance fifo_autoDatacollection_inst
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells fifo_autoDatacollection_inst]
current_instance {genCh[2].fifo_adcData_ch}
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {genCh[2].fifo_adcData_ch}]
current_instance {genCh[1].fifo_adcData_ch}
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {genCh[1].fifo_adcData_ch}]
current_instance {genCh[0].fifo_adcData_ch}
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {genCh[0].fifo_adcData_ch}]
current_instance ila_xadc_all
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells ila_xadc_all]
current_instance ila_xadc_fifoAutoSparse
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells ila_xadc_fifoAutoSparse]
current_instance ila_xadc_fifoAuto
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells ila_xadc_fifoAuto]
current_instance ila_xadc_controller
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells ila_xadc_controller]
current_instance {genCh[2].ila_xadc_ch}
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {genCh[2].ila_xadc_ch}]
current_instance {genCh[1].ila_xadc_ch}
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {genCh[1].ila_xadc_ch}]
current_instance {genCh[0].ila_xadc_ch}
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {genCh[0].ila_xadc_ch}]
current_instance xadc_senseWire_inst
set_property src_info {type:SCOPED_XDC file:14 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance m_axis_aclk]
current_instance
set_property src_info {type:SCOPED_XDC file:14 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells xadc_senseWire_inst]
set_property src_info {type:XDC file:15 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports V_p]
set_property src_info {type:XDC file:15 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports Vaux8_p]
set_property src_info {type:XDC file:15 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sysclk_p]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells clk_sysclk_mmcm_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells vio_ctrl_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells fifo_autoDatacollection_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {genCh[0].fifo_adcData_ch}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {genCh[1].fifo_adcData_ch}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {genCh[2].fifo_adcData_ch}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {genCh[0].ila_xadc_ch}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {genCh[1].ila_xadc_ch}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {genCh[2].ila_xadc_ch}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ila_xadc_all]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ila_xadc_controller]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ila_xadc_fifoAuto]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ila_xadc_fifoAutoSparse]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells xadc_senseWire_inst]
