set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/blkMem_mainsAvg/blkMem_mainsAvg/blkMem_mainsAvg_in_context.xdc rfile:../../../../source/cores/ipMicrozed/blkMem_mainsAvg/blkMem_mainsAvg/blkMem_mainsAvg_in_context.xdc id:1 order:EARLY scoped_inst:top_tension_analyzer_1/wtaController_inst/blkMem_mainsAvg_inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/clk_sysclk_mmcm/clk_sysclk_mmcm/clk_sysclk_mmcm_in_context.xdc rfile:../../../../source/cores/ipMicrozed/clk_sysclk_mmcm/clk_sysclk_mmcm/clk_sysclk_mmcm_in_context.xdc id:2 order:EARLY scoped_inst:top_tension_analyzer_1/clk_sysclk_mmcm_inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/fifo_autoDatacollection/fifo_autoDatacollection/fifo_autoDatacollection_in_context.xdc rfile:../../../../source/cores/ipMicrozed/fifo_autoDatacollection/fifo_autoDatacollection/fifo_autoDatacollection_in_context.xdc id:3 order:EARLY scoped_inst:top_tension_analyzer_1/fifo_autoDatacollection_inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/fifo_adcData/fifo_adcData/fifo_adcData_in_context.xdc rfile:../../../../source/cores/ipMicrozed/fifo_adcData/fifo_adcData/fifo_adcData_in_context.xdc id:4 order:EARLY scoped_inst:{top_tension_analyzer_1/genCh[2].fifo_adcData_ch}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/fifo_adcData/fifo_adcData/fifo_adcData_in_context.xdc rfile:../../../../source/cores/ipMicrozed/fifo_adcData/fifo_adcData/fifo_adcData_in_context.xdc id:5 order:EARLY scoped_inst:{top_tension_analyzer_1/genCh[1].fifo_adcData_ch}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/fifo_adcData/fifo_adcData/fifo_adcData_in_context.xdc rfile:../../../../source/cores/ipMicrozed/fifo_adcData/fifo_adcData/fifo_adcData_in_context.xdc id:6 order:EARLY scoped_inst:{top_tension_analyzer_1/genCh[0].fifo_adcData_ch}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/ila_xadc/ila_xadc/ila_xadc_in_context.xdc rfile:../../../../source/cores/ipMicrozed/ila_xadc/ila_xadc/ila_xadc_in_context.xdc id:7 order:EARLY scoped_inst:top_tension_analyzer_1/ila_xadc_all} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/ila_xadc/ila_xadc/ila_xadc_in_context.xdc rfile:../../../../source/cores/ipMicrozed/ila_xadc/ila_xadc/ila_xadc_in_context.xdc id:8 order:EARLY scoped_inst:top_tension_analyzer_1/ila_xadc_fifoAuto} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/ila_xadc/ila_xadc/ila_xadc_in_context.xdc rfile:../../../../source/cores/ipMicrozed/ila_xadc/ila_xadc/ila_xadc_in_context.xdc id:9 order:EARLY scoped_inst:top_tension_analyzer_1/ila_xadc_controller} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/ila_xadc/ila_xadc/ila_xadc_in_context.xdc rfile:../../../../source/cores/ipMicrozed/ila_xadc/ila_xadc/ila_xadc_in_context.xdc id:10 order:EARLY scoped_inst:{top_tension_analyzer_1/genCh[2].ila_xadc_ch}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/ila_xadc/ila_xadc/ila_xadc_in_context.xdc rfile:../../../../source/cores/ipMicrozed/ila_xadc/ila_xadc/ila_xadc_in_context.xdc id:11 order:EARLY scoped_inst:{top_tension_analyzer_1/genCh[1].ila_xadc_ch}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/ila_xadc/ila_xadc/ila_xadc_in_context.xdc rfile:../../../../source/cores/ipMicrozed/ila_xadc/ila_xadc/ila_xadc_in_context.xdc id:12 order:EARLY scoped_inst:{top_tension_analyzer_1/genCh[0].ila_xadc_ch}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/ila_xadc_big/ila_xadc_big/ila_xadc_big_in_context.xdc rfile:../../../../source/cores/ipMicrozed/ila_xadc_big/ila_xadc_big/ila_xadc_big_in_context.xdc id:13 order:EARLY scoped_inst:top_tension_analyzer_1/ila_xadc_fifoAutoSparse} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/cores/ipMicrozed/xadc_senseWire/xadc_senseWire/xadc_senseWire_in_context.xdc rfile:../../../../source/cores/ipMicrozed/xadc_senseWire/xadc_senseWire/xadc_senseWire_in_context.xdc id:14 order:EARLY scoped_inst:top_tension_analyzer_1/xadc_senseWire_inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/dwa_ps_bd/dwa_ps_bd_in_context.xdc rfile:../../../../../vivadoProjects/dwa_ps/dwa_ps.srcs/sources_1/bd/dwa_ps_bd/dwa_ps_bd/dwa_ps_bd_in_context.xdc id:15 order:EARLY scoped_inst:dwa_ps_bd_i} [current_design]
set_property SRC_FILE_INFO {cfile:/home/nate/projects/duneWireTension/firmware/source/constraints/tensionAnalyzerMicrozedPl.xdc rfile:../../../../source/constraints/tensionAnalyzerMicrozedPl.xdc id:16} [current_design]
current_instance top_tension_analyzer_1/wtaController_inst/blkMem_mainsAvg_inst
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_ports -scoped_to_current_instance clka]
current_instance
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells top_tension_analyzer_1/wtaController_inst/blkMem_mainsAvg_inst]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name BB_CLK [get_ports BB_CLK]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name top_tension_analyzer_1/clk_sysclk_mmcm_inst/clk_out1 -source [get_ports BB_CLK] -edges {1 2 3} -edge_shift {0.000 15.000 30.000} [get_pins top_tension_analyzer_1/clk_sysclk_mmcm_inst/clk_out1]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name top_tension_analyzer_1/clk_sysclk_mmcm_inst/clk_out2 -source [get_ports BB_CLK] -edges {1 2 3} -edge_shift {0.000 5.000 10.000} [get_pins top_tension_analyzer_1/clk_sysclk_mmcm_inst/clk_out2]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name top_tension_analyzer_1/clk_sysclk_mmcm_inst/clk_out3 -source [get_ports BB_CLK] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins top_tension_analyzer_1/clk_sysclk_mmcm_inst/clk_out3]
set_property src_info {type:SCOPED_XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name top_tension_analyzer_1/clk_sysclk_mmcm_inst/clk_out4 -source [get_ports BB_CLK] -edges {1 2 3} -edge_shift {0.000 -2.500 -5.000} [get_pins top_tension_analyzer_1/clk_sysclk_mmcm_inst/clk_out4]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name top_tension_analyzer_1/clk_sysclk_mmcm_inst/clk_out5 -source [get_ports BB_CLK] -edges {1 2 3} -edge_shift {0.000 -3.750 -7.500} [get_pins top_tension_analyzer_1/clk_sysclk_mmcm_inst/clk_out5]
set_property src_info {type:SCOPED_XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name top_tension_analyzer_1/clk_sysclk_mmcm_inst/clk_out6 -source [get_ports BB_CLK] -edges {1 2 3} -edge_shift {0.000 35.000 70.000} [get_pins top_tension_analyzer_1/clk_sysclk_mmcm_inst/clk_out6]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports BB_CLK]
set_property src_info {type:SCOPED_XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports BB_CLK]
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells top_tension_analyzer_1/clk_sysclk_mmcm_inst]
current_instance top_tension_analyzer_1/fifo_autoDatacollection_inst
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells top_tension_analyzer_1/fifo_autoDatacollection_inst]
current_instance {top_tension_analyzer_1/genCh[2].fifo_adcData_ch}
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {top_tension_analyzer_1/genCh[2].fifo_adcData_ch}]
current_instance {top_tension_analyzer_1/genCh[1].fifo_adcData_ch}
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {top_tension_analyzer_1/genCh[1].fifo_adcData_ch}]
current_instance {top_tension_analyzer_1/genCh[0].fifo_adcData_ch}
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {top_tension_analyzer_1/genCh[0].fifo_adcData_ch}]
current_instance top_tension_analyzer_1/ila_xadc_all
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells top_tension_analyzer_1/ila_xadc_all]
current_instance top_tension_analyzer_1/ila_xadc_fifoAuto
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells top_tension_analyzer_1/ila_xadc_fifoAuto]
current_instance top_tension_analyzer_1/ila_xadc_controller
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells top_tension_analyzer_1/ila_xadc_controller]
current_instance {top_tension_analyzer_1/genCh[2].ila_xadc_ch}
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {top_tension_analyzer_1/genCh[2].ila_xadc_ch}]
current_instance {top_tension_analyzer_1/genCh[1].ila_xadc_ch}
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {top_tension_analyzer_1/genCh[1].ila_xadc_ch}]
current_instance {top_tension_analyzer_1/genCh[0].ila_xadc_ch}
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {top_tension_analyzer_1/genCh[0].ila_xadc_ch}]
current_instance top_tension_analyzer_1/ila_xadc_fifoAutoSparse
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance clk]
current_instance
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells top_tension_analyzer_1/ila_xadc_fifoAutoSparse]
current_instance top_tension_analyzer_1/xadc_senseWire_inst
set_property src_info {type:SCOPED_XDC file:14 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance m_axis_aclk]
current_instance
set_property src_info {type:SCOPED_XDC file:14 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells top_tension_analyzer_1/xadc_senseWire_inst]
set_property src_info {type:SCOPED_XDC file:15 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name dwa_ps_bd_i/aclk [get_pins dwa_ps_bd_i/aclk]
set_property src_info {type:SCOPED_XDC file:15 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[10]}]
set_property src_info {type:SCOPED_XDC file:15 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[10]}]
set_property src_info {type:SCOPED_XDC file:15 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[11]}]
set_property src_info {type:SCOPED_XDC file:15 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[11]}]
set_property src_info {type:SCOPED_XDC file:15 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[12]}]
set_property src_info {type:SCOPED_XDC file:15 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[12]}]
set_property src_info {type:SCOPED_XDC file:15 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[13]}]
set_property src_info {type:SCOPED_XDC file:15 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[13]}]
set_property src_info {type:SCOPED_XDC file:15 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[14]}]
set_property src_info {type:SCOPED_XDC file:15 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[14]}]
set_property src_info {type:SCOPED_XDC file:15 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[3]}]
set_property src_info {type:SCOPED_XDC file:15 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[3]}]
set_property src_info {type:SCOPED_XDC file:15 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[4]}]
set_property src_info {type:SCOPED_XDC file:15 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[4]}]
set_property src_info {type:SCOPED_XDC file:15 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[5]}]
set_property src_info {type:SCOPED_XDC file:15 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[5]}]
set_property src_info {type:SCOPED_XDC file:15 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[6]}]
set_property src_info {type:SCOPED_XDC file:15 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[6]}]
set_property src_info {type:SCOPED_XDC file:15 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[7]}]
set_property src_info {type:SCOPED_XDC file:15 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[7]}]
set_property src_info {type:SCOPED_XDC file:15 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[8]}]
set_property src_info {type:SCOPED_XDC file:15 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[8]}]
set_property src_info {type:SCOPED_XDC file:15 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_addr[9]}]
set_property src_info {type:SCOPED_XDC file:15 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_addr[9]}]
set_property src_info {type:SCOPED_XDC file:15 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_ba[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_ba[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_ba[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_ba[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_ba[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_ba[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports DDR_cas_n]
set_property src_info {type:SCOPED_XDC file:15 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports DDR_cas_n]
set_property src_info {type:SCOPED_XDC file:15 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports DDR_ck_n]
set_property src_info {type:SCOPED_XDC file:15 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports DDR_ck_n]
set_property src_info {type:SCOPED_XDC file:15 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports DDR_ck_p]
set_property src_info {type:SCOPED_XDC file:15 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports DDR_ck_p]
set_property src_info {type:SCOPED_XDC file:15 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports DDR_cke]
set_property src_info {type:SCOPED_XDC file:15 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports DDR_cke]
set_property src_info {type:SCOPED_XDC file:15 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports DDR_cs_n]
set_property src_info {type:SCOPED_XDC file:15 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports DDR_cs_n]
set_property src_info {type:SCOPED_XDC file:15 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dm[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dm[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dm[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dm[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dm[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dm[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dm[3]}]
set_property src_info {type:SCOPED_XDC file:15 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dm[3]}]
set_property src_info {type:SCOPED_XDC file:15 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[10]}]
set_property src_info {type:SCOPED_XDC file:15 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[10]}]
set_property src_info {type:SCOPED_XDC file:15 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[11]}]
set_property src_info {type:SCOPED_XDC file:15 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[11]}]
set_property src_info {type:SCOPED_XDC file:15 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[12]}]
set_property src_info {type:SCOPED_XDC file:15 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[12]}]
set_property src_info {type:SCOPED_XDC file:15 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[13]}]
set_property src_info {type:SCOPED_XDC file:15 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[13]}]
set_property src_info {type:SCOPED_XDC file:15 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[14]}]
set_property src_info {type:SCOPED_XDC file:15 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[14]}]
set_property src_info {type:SCOPED_XDC file:15 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[15]}]
set_property src_info {type:SCOPED_XDC file:15 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[15]}]
set_property src_info {type:SCOPED_XDC file:15 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[16]}]
set_property src_info {type:SCOPED_XDC file:15 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[16]}]
set_property src_info {type:SCOPED_XDC file:15 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[17]}]
set_property src_info {type:SCOPED_XDC file:15 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[17]}]
set_property src_info {type:SCOPED_XDC file:15 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[18]}]
set_property src_info {type:SCOPED_XDC file:15 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[18]}]
set_property src_info {type:SCOPED_XDC file:15 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[19]}]
set_property src_info {type:SCOPED_XDC file:15 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[19]}]
set_property src_info {type:SCOPED_XDC file:15 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[20]}]
set_property src_info {type:SCOPED_XDC file:15 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[20]}]
set_property src_info {type:SCOPED_XDC file:15 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[21]}]
set_property src_info {type:SCOPED_XDC file:15 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[21]}]
set_property src_info {type:SCOPED_XDC file:15 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[22]}]
set_property src_info {type:SCOPED_XDC file:15 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[22]}]
set_property src_info {type:SCOPED_XDC file:15 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[23]}]
set_property src_info {type:SCOPED_XDC file:15 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[23]}]
set_property src_info {type:SCOPED_XDC file:15 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[24]}]
set_property src_info {type:SCOPED_XDC file:15 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[24]}]
set_property src_info {type:SCOPED_XDC file:15 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[25]}]
set_property src_info {type:SCOPED_XDC file:15 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[25]}]
set_property src_info {type:SCOPED_XDC file:15 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[26]}]
set_property src_info {type:SCOPED_XDC file:15 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[26]}]
set_property src_info {type:SCOPED_XDC file:15 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[27]}]
set_property src_info {type:SCOPED_XDC file:15 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[27]}]
set_property src_info {type:SCOPED_XDC file:15 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[28]}]
set_property src_info {type:SCOPED_XDC file:15 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[28]}]
set_property src_info {type:SCOPED_XDC file:15 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[29]}]
set_property src_info {type:SCOPED_XDC file:15 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[29]}]
set_property src_info {type:SCOPED_XDC file:15 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[30]}]
set_property src_info {type:SCOPED_XDC file:15 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[30]}]
set_property src_info {type:SCOPED_XDC file:15 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[31]}]
set_property src_info {type:SCOPED_XDC file:15 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[31]}]
set_property src_info {type:SCOPED_XDC file:15 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[3]}]
set_property src_info {type:SCOPED_XDC file:15 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[3]}]
set_property src_info {type:SCOPED_XDC file:15 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[4]}]
set_property src_info {type:SCOPED_XDC file:15 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[4]}]
set_property src_info {type:SCOPED_XDC file:15 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[5]}]
set_property src_info {type:SCOPED_XDC file:15 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[5]}]
set_property src_info {type:SCOPED_XDC file:15 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[6]}]
set_property src_info {type:SCOPED_XDC file:15 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[6]}]
set_property src_info {type:SCOPED_XDC file:15 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[7]}]
set_property src_info {type:SCOPED_XDC file:15 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[7]}]
set_property src_info {type:SCOPED_XDC file:15 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[8]}]
set_property src_info {type:SCOPED_XDC file:15 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[8]}]
set_property src_info {type:SCOPED_XDC file:15 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dq[9]}]
set_property src_info {type:SCOPED_XDC file:15 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dq[9]}]
set_property src_info {type:SCOPED_XDC file:15 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:15 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:15 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:15 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:15 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports DDR_odt]
set_property src_info {type:SCOPED_XDC file:15 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports DDR_odt]
set_property src_info {type:SCOPED_XDC file:15 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports DDR_ras_n]
set_property src_info {type:SCOPED_XDC file:15 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports DDR_ras_n]
set_property src_info {type:SCOPED_XDC file:15 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports DDR_reset_n]
set_property src_info {type:SCOPED_XDC file:15 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports DDR_reset_n]
set_property src_info {type:SCOPED_XDC file:15 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports DDR_we_n]
set_property src_info {type:SCOPED_XDC file:15 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports DDR_we_n]
set_property src_info {type:SCOPED_XDC file:15 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports FIXED_IO_ddr_vrn]
set_property src_info {type:SCOPED_XDC file:15 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports FIXED_IO_ddr_vrn]
set_property src_info {type:SCOPED_XDC file:15 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports FIXED_IO_ddr_vrp]
set_property src_info {type:SCOPED_XDC file:15 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports FIXED_IO_ddr_vrp]
set_property src_info {type:SCOPED_XDC file:15 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[0]}]
set_property src_info {type:SCOPED_XDC file:15 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[10]}]
set_property src_info {type:SCOPED_XDC file:15 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[10]}]
set_property src_info {type:SCOPED_XDC file:15 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[11]}]
set_property src_info {type:SCOPED_XDC file:15 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[11]}]
set_property src_info {type:SCOPED_XDC file:15 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[12]}]
set_property src_info {type:SCOPED_XDC file:15 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[12]}]
set_property src_info {type:SCOPED_XDC file:15 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[13]}]
set_property src_info {type:SCOPED_XDC file:15 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[13]}]
set_property src_info {type:SCOPED_XDC file:15 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[14]}]
set_property src_info {type:SCOPED_XDC file:15 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[14]}]
set_property src_info {type:SCOPED_XDC file:15 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[15]}]
set_property src_info {type:SCOPED_XDC file:15 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[15]}]
set_property src_info {type:SCOPED_XDC file:15 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[16]}]
set_property src_info {type:SCOPED_XDC file:15 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[16]}]
set_property src_info {type:SCOPED_XDC file:15 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[17]}]
set_property src_info {type:SCOPED_XDC file:15 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[17]}]
set_property src_info {type:SCOPED_XDC file:15 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[18]}]
set_property src_info {type:SCOPED_XDC file:15 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[18]}]
set_property src_info {type:SCOPED_XDC file:15 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[19]}]
set_property src_info {type:SCOPED_XDC file:15 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[19]}]
set_property src_info {type:SCOPED_XDC file:15 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[1]}]
set_property src_info {type:SCOPED_XDC file:15 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[20]}]
set_property src_info {type:SCOPED_XDC file:15 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[20]}]
set_property src_info {type:SCOPED_XDC file:15 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[21]}]
set_property src_info {type:SCOPED_XDC file:15 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[21]}]
set_property src_info {type:SCOPED_XDC file:15 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[22]}]
set_property src_info {type:SCOPED_XDC file:15 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[22]}]
set_property src_info {type:SCOPED_XDC file:15 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[23]}]
set_property src_info {type:SCOPED_XDC file:15 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[23]}]
set_property src_info {type:SCOPED_XDC file:15 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[24]}]
set_property src_info {type:SCOPED_XDC file:15 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[24]}]
set_property src_info {type:SCOPED_XDC file:15 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[25]}]
set_property src_info {type:SCOPED_XDC file:15 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[25]}]
set_property src_info {type:SCOPED_XDC file:15 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[26]}]
set_property src_info {type:SCOPED_XDC file:15 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[26]}]
set_property src_info {type:SCOPED_XDC file:15 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[27]}]
set_property src_info {type:SCOPED_XDC file:15 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[27]}]
set_property src_info {type:SCOPED_XDC file:15 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[28]}]
set_property src_info {type:SCOPED_XDC file:15 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[28]}]
set_property src_info {type:SCOPED_XDC file:15 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[29]}]
set_property src_info {type:SCOPED_XDC file:15 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[29]}]
set_property src_info {type:SCOPED_XDC file:15 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[2]}]
set_property src_info {type:SCOPED_XDC file:15 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[30]}]
set_property src_info {type:SCOPED_XDC file:15 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[30]}]
set_property src_info {type:SCOPED_XDC file:15 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[31]}]
set_property src_info {type:SCOPED_XDC file:15 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[31]}]
set_property src_info {type:SCOPED_XDC file:15 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[32]}]
set_property src_info {type:SCOPED_XDC file:15 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[32]}]
set_property src_info {type:SCOPED_XDC file:15 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[33]}]
set_property src_info {type:SCOPED_XDC file:15 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[33]}]
set_property src_info {type:SCOPED_XDC file:15 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[34]}]
set_property src_info {type:SCOPED_XDC file:15 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[34]}]
set_property src_info {type:SCOPED_XDC file:15 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[35]}]
set_property src_info {type:SCOPED_XDC file:15 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[35]}]
set_property src_info {type:SCOPED_XDC file:15 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[36]}]
set_property src_info {type:SCOPED_XDC file:15 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[36]}]
set_property src_info {type:SCOPED_XDC file:15 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[37]}]
set_property src_info {type:SCOPED_XDC file:15 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[37]}]
set_property src_info {type:SCOPED_XDC file:15 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[38]}]
set_property src_info {type:SCOPED_XDC file:15 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[38]}]
set_property src_info {type:SCOPED_XDC file:15 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[39]}]
set_property src_info {type:SCOPED_XDC file:15 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[39]}]
set_property src_info {type:SCOPED_XDC file:15 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[3]}]
set_property src_info {type:SCOPED_XDC file:15 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[3]}]
set_property src_info {type:SCOPED_XDC file:15 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[40]}]
set_property src_info {type:SCOPED_XDC file:15 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[40]}]
set_property src_info {type:SCOPED_XDC file:15 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[41]}]
set_property src_info {type:SCOPED_XDC file:15 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[41]}]
set_property src_info {type:SCOPED_XDC file:15 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[42]}]
set_property src_info {type:SCOPED_XDC file:15 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[42]}]
set_property src_info {type:SCOPED_XDC file:15 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[43]}]
set_property src_info {type:SCOPED_XDC file:15 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[43]}]
set_property src_info {type:SCOPED_XDC file:15 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[44]}]
set_property src_info {type:SCOPED_XDC file:15 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[44]}]
set_property src_info {type:SCOPED_XDC file:15 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[45]}]
set_property src_info {type:SCOPED_XDC file:15 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[45]}]
set_property src_info {type:SCOPED_XDC file:15 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[46]}]
set_property src_info {type:SCOPED_XDC file:15 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[46]}]
set_property src_info {type:SCOPED_XDC file:15 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[47]}]
set_property src_info {type:SCOPED_XDC file:15 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[47]}]
set_property src_info {type:SCOPED_XDC file:15 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[48]}]
set_property src_info {type:SCOPED_XDC file:15 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[48]}]
set_property src_info {type:SCOPED_XDC file:15 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[49]}]
set_property src_info {type:SCOPED_XDC file:15 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[49]}]
set_property src_info {type:SCOPED_XDC file:15 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[4]}]
set_property src_info {type:SCOPED_XDC file:15 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[4]}]
set_property src_info {type:SCOPED_XDC file:15 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[50]}]
set_property src_info {type:SCOPED_XDC file:15 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[50]}]
set_property src_info {type:SCOPED_XDC file:15 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[51]}]
set_property src_info {type:SCOPED_XDC file:15 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[51]}]
set_property src_info {type:SCOPED_XDC file:15 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[52]}]
set_property src_info {type:SCOPED_XDC file:15 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[52]}]
set_property src_info {type:SCOPED_XDC file:15 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[53]}]
set_property src_info {type:SCOPED_XDC file:15 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[53]}]
set_property src_info {type:SCOPED_XDC file:15 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[5]}]
set_property src_info {type:SCOPED_XDC file:15 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[5]}]
set_property src_info {type:SCOPED_XDC file:15 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[6]}]
set_property src_info {type:SCOPED_XDC file:15 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[6]}]
set_property src_info {type:SCOPED_XDC file:15 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[7]}]
set_property src_info {type:SCOPED_XDC file:15 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[7]}]
set_property src_info {type:SCOPED_XDC file:15 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[8]}]
set_property src_info {type:SCOPED_XDC file:15 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[8]}]
set_property src_info {type:SCOPED_XDC file:15 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[9]}]
set_property src_info {type:SCOPED_XDC file:15 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {FIXED_IO_mio[9]}]
set_property src_info {type:SCOPED_XDC file:15 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports FIXED_IO_ps_clk]
set_property src_info {type:SCOPED_XDC file:15 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports FIXED_IO_ps_clk]
set_property src_info {type:SCOPED_XDC file:15 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports FIXED_IO_ps_porb]
set_property src_info {type:SCOPED_XDC file:15 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports FIXED_IO_ps_porb]
set_property src_info {type:SCOPED_XDC file:15 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports FIXED_IO_ps_srstb]
set_property src_info {type:SCOPED_XDC file:15 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports FIXED_IO_ps_srstb]
current_instance dwa_ps_bd_i
set_property src_info {type:SCOPED_XDC file:15 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance aclk]
current_instance
set_property src_info {type:SCOPED_XDC file:15 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells dwa_ps_bd_i]
set_property src_info {type:XDC file:16 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports acStim_obuf]
set_property src_info {type:XDC file:16 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports acStimX200_obuf]
set_property src_info {type:XDC file:16 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports V_p]
set_property src_info {type:XDC file:16 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports Vaux8_p]
set_property src_info {type:XDC file:16 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports BB_CLK]
set_property src_info {type:XDC file:16 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports BB_CLK_EN]
set_property src_info {type:XDC file:16 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
set_property src_info {type:XDC file:16 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
set_property src_info {type:XDC file:16 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]
set_property src_info {type:XDC file:16 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {led[3]}]
set_property src_info {type:XDC file:16 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports mainsSquare]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells top_tension_analyzer_1/wtaController_inst/blkMem_mainsAvg_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells top_tension_analyzer_1/clk_sysclk_mmcm_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells top_tension_analyzer_1/fifo_autoDatacollection_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {top_tension_analyzer_1/genCh[0].fifo_adcData_ch}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {top_tension_analyzer_1/genCh[1].fifo_adcData_ch}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {top_tension_analyzer_1/genCh[2].fifo_adcData_ch}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {top_tension_analyzer_1/genCh[0].ila_xadc_ch}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {top_tension_analyzer_1/genCh[1].ila_xadc_ch}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {top_tension_analyzer_1/genCh[2].ila_xadc_ch}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells top_tension_analyzer_1/ila_xadc_all]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells top_tension_analyzer_1/ila_xadc_controller]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells top_tension_analyzer_1/ila_xadc_fifoAuto]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells top_tension_analyzer_1/ila_xadc_fifoAutoSparse]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells top_tension_analyzer_1/xadc_senseWire_inst]
