######################################################################
#
# File name : tb_axi_file_io_compile.do
# Created on: Fri May 26 11:38:12 EDT 2017
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib
vlib msim/ATLAS_MMTP

vmap xil_defaultlib msim/xil_defaultlib
vmap ATLAS_MMTP msim/ATLAS_MMTP

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../firmware/sources/cores/ip/clk40_pll" "+incdir+../../../../../firmware/sources/cores/ip/mmcm_usr_clk" "+incdir+../../../mm_top.srcs/sources_1/ip/clk_mmfe_sync" \
"../../../../../firmware/sources/cores/ip/blk_mem_gbt_pkt_delay/sim/blk_mem_gbt_pkt_delay.v" \
"../../../../../firmware/sources/cores/ip/blk_mem_gen_mxlocalC_CRTS/sim/blk_mem_gen_mxlocalC_CRTS.v" \
"../../../../../firmware/sources/cores/ip/clk40_pll/clk40_pll_clk_wiz.v" \
"../../../../../firmware/sources/cores/ip/clk40_pll/clk40_pll.v" \
"../../../../../firmware/sources/cores/ip/dist_mem_16_14/sim/dist_mem_16_14.v" \
"../../../../../firmware/sources/cores/ip/dist_mem_16_16/sim/dist_mem_16_16.v" \

vcom -64 -93 -work xil_defaultlib  \
"../../../../../firmware/sources/cores/ip/dsp48_add_mult_no_out_reg/sim/dsp48_add_mult_no_out_reg.vhd" \
"../../../../../firmware/sources/cores/ip/dsp48_add_mult_px/sim/dsp48_add_mult_px.vhd" \

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../firmware/sources/cores/ip/clk40_pll" "+incdir+../../../../../firmware/sources/cores/ip/mmcm_usr_clk" "+incdir+../../../mm_top.srcs/sources_1/ip/clk_mmfe_sync" \
"../../../../../firmware/sources/cores/ip/fifo_w128_r32_d16/sim/fifo_w128_r32_d16.v" \
"../../../../../firmware/sources/cores/ip/fifo_w16_r16_d16/sim/fifo_w16_r16_d16.v" \
"../../../../../firmware/sources/cores/ip/fifo_w256_r32/sim/fifo_w256_r32.v" \
"../../../../../firmware/sources/cores/ip/fifo_w32_r128/sim/fifo_w32_r128.v" \
"../../../../../firmware/sources/cores/ip/fifo_w32_r32_d16/sim/fifo_w32_r32_d16.v" \
"../../../../../firmware/sources/cores/ip/fifo_w4_r4_d16/sim/fifo_w4_r4_d16.v" \

vcom -64 -93 -work xil_defaultlib  \
"../../../../../firmware/sources/cores/ip/mult_S16_U16_32/sim/mult_S16_U16_32.vhd" \
"../../../../../firmware/sources/cores/ip/mult_U16_U16_32/sim/mult_U16_U16_32.vhd" \
"../../../../../firmware/sources/cores/ip/mult_u14_u16_16/sim/mult_u14_u16_16.vhd" \

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../firmware/sources/cores/ip/clk40_pll" "+incdir+../../../../../firmware/sources/cores/ip/mmcm_usr_clk" "+incdir+../../../mm_top.srcs/sources_1/ip/clk_mmfe_sync" \
"../../../../../firmware/sources/cores/ip/rom_d_theta_mx_recip/sim/rom_d_theta_mx_recip.v" \
"../../../../../firmware/sources/cores/ip/rom_roi_map/sim/rom_roi_map.v" \

vcom -64 -93 -work xil_defaultlib  \
"../../../../../firmware/sources/cores/ip/xbip_axb_pcin_regout/sim/xbip_axb_pcin_regout.vhd" \
"../../../../../firmware/sources/cores/ip/xbip_axb_pcout_no_regout/sim/xbip_axb_pcout_no_regout.vhd" \

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../firmware/sources/cores/ip/clk40_pll" "+incdir+../../../../../firmware/sources/cores/ip/mmcm_usr_clk" "+incdir+../../../mm_top.srcs/sources_1/ip/clk_mmfe_sync" \
"../../../mm_top.srcs/sources_1/ip/clk_mmfe_sync/clk_mmfe_sync_clk_wiz.v" \
"../../../mm_top.srcs/sources_1/ip/clk_mmfe_sync/clk_mmfe_sync.v" \
"../../../mm_top.srcs/sources_1/ip/fifo_w64_r32_d16/sim/fifo_w64_r32_d16.v" \

vcom -64 -93 -work ATLAS_MMTP  \
"../../../../../firmware/sources/packages/xlx_k7v7_gbt_bank_package.vhd" \
"../../../../../firmware/sources/packages/xlx_k7v7_gbt_banks_user_setup.vhd" \
"../../../../../firmware/sources/packages/global_def.vhd" \
"../../../../../firmware/sources/packages/lppc_custom_fn_pkg.vhd" \
"../../../../../firmware/sources/hdl/common/standard_mux16.vhd" \
"../../../../../firmware/sources/hdl/common/mux16_vector9.vhd" \
"../../../../../firmware/sources/hdl/common/mux16_nibb.vhd" \

vcom -64 -2008 -work ATLAS_MMTP  \
"../../../../../firmware/sources/hdl/common/data_collector_scint_timestamp.vhd" \
"../../../../../firmware/sources/hdl/common/data_collector_hits.vhd" \

vcom -64 -93 -work ATLAS_MMTP  \
"../../../../../firmware/sources/hdl/common/data_collector_track.vhd" \
"../../../../../firmware/sources/hdl/common/data_collector_fitter.vhd" \
"../../../../../firmware/sources/hdl/common/monitoring_gbt_pkts.vhd" \
"../../../../../firmware/sources/hdl/gbtDecode/gbt_decode_priority_encode_cell.vhd" \
"../../../../../firmware/sources/hdl/gbtDecode/gbt_decode_priority_encode.vhd" \
"../../../../../firmware/sources/hdl/gbtDecode/gbt_decode_priority_select.vhd" \
"../../../../../firmware/sources/hdl/gbtDecode/gbt_decode_calc_slope.vhd" \
"../../../../../firmware/sources/hdl/gbtDecode/gbt_decode.vhd" \
"../../../../../firmware/sources/hdl/finder/fifo_16_16_4.vhd" \
"../../../../../firmware/sources/hdl/finder/apfind_hit_mark.vhd" \
"../../../../../firmware/sources/hdl/finder/apfind_plane.vhd" \
"../../../../../firmware/sources/hdl/finder/apfind_hit_buff.vhd" \
"../../../../../firmware/sources/hdl/finder/apfind_road16x8.vhd" \
"../../../../../firmware/sources/hdl/finder/apfind_region.vhd" \
"../../../../../firmware/sources/hdl/fitter/xip_avg.vhd" \
"../../../../../firmware/sources/hdl/fitter/bin_tree_add.vhd" \
"../../../../../firmware/sources/hdl/fitter/bin_tree_avg_s.vhd" \
"../../../../../firmware/sources/hdl/fitter/calc_roi_struct.vhd" \
"../../../../../firmware/sources/hdl/fitter/calc_mx_local_behav.vhd" \
"../../../../../firmware/sources/hdl/fitter/calc_dtheta.vhd" \
"../../../../../firmware/sources/hdl/fitter/top_fitter.vhd" \

vcom -64 -2008 -work ATLAS_MMTP  \
"../../../../../firmware/sources/hdl/top_mmtpp_struct.vhd" \

vcom -64 -93 -work ATLAS_MMTP  \
"../../../../../firmware/sources/hdl/common/mmtp_ctrl.vhd" \

vcom -64 -2008 -work ATLAS_MMTP  \
"../../../../../firmware/sources/hdl/common/mmtp_axi.vhd" \

vcom -64 -93 -work ATLAS_MMTP  \
"../../../../../firmware/sources/simulation/axi_file_io.vhd" \
"../../../../../firmware/sources/simulation/tb_axi_file_io.vhd" \

# compile glbl module
vlog -work ATLAS_MMTP "glbl.v"

